### ISSUE TITLE
Parquet Support ?

### ISSUE THREAD

**Issue by blackrez** [suketa/ruby-duckdb#225]
Hello,

I'm trying to use ruby-duckdb but I can't use parquet_scan function. Is parquet supported ?

```
parallels@ubuntu-linux-20-04-desktop:~/Desktop/Parallels Shared Folders/Home/project/monplein$ irb
3.0.0 :001 > require "duckdb"
 => true 
3.0.0 :002 > db = DuckDB::Database.open
 => #<DuckDB::Database:0x0000aaaaccd56660> 
3.0.0 :003 > con = db.connect
 => #<DuckDB::Connection:0x0000aaaaccdddfc0> 
3.0.0 :004 > con.query("CREATE TABLE station_gas AS SELECT * FROM parquet_scan('
file.parquet')")
Traceback (most recent call last):
        6: from /usr/share/rvm/rubies/ruby-3.0.0/bin/irb:23:in `<main>'
        5: from /usr/share/rvm/rubies/ruby-3.0.0/bin/irb:23:in `load'
        4: from /usr/share/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        3: from (irb):4:in `<main>'
        2: from /usr/share/rvm/gems/ruby-3.0.0/gems/duckdb-0.2.9.0/lib/duckdb/connection.rb:23:in `query'
        1: from /usr/share/rvm/gems/ruby-3.0.0/gems/duckdb-0.2.9.0/lib/duckdb/connection.rb:23:in `query_sql'
DuckDB::Error (Catalog Error: Table Function with name parquet_scan does not exist!)
Did you mean "arrow_scan"?
LINE 1: ...ATE TABLE station_gas AS SELECT * FROM parquet_scan('file.parquet')
                                                  ^
3.0.0 :005 > 
```

With the duckdb binary, I haven't any issue.

```
parallels@ubuntu-linux-20-04-desktop:~/Desktop/Parallels Shared Folders/Home/project/monplein$ duckdb
v0.0.1-dev0 
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE station_gas AS SELECT * FROM parquet_scan('file.parquet');
D select count(1) from station_gas;
┌──────────┐
│ count(1) │
├──────────┤
│ 3324810  │
└──────────┘

```

**Comment by blackrez** [comment]
Found the root cause, the C API doesn't expose the extension (and parquet is one of them).

**Comment by blackrez** [comment]
Duckdb team pushed a fix. I will test it. https://github.com/duckdb/duckdb/pull/2563

**Comment by blackrez** [comment]
YEAH it's working.

```
3.0.0 :003 > db = DuckDB::Database.open 
 => #<DuckDB::Database:0x0000aaaabe984bf8> 
3.0.0 :004 > con = db.connect
 => #<DuckDB::Connection:0x0000aaaabe98d3e8> 
3.0.0 :005 > con.query("CREATE TABLE station_gas AS SELECT * FROM parquet_scan('
file.parquet')")
 => #<DuckDB::Result:0x0000aaaabe6640e0> 
3.0.0 :006 > 
```

**Comment by blackrez** [comment]
With the master version.
