### ISSUE TITLE
failed append_blob with duckdb 0.4.0

### ISSUE THREAD

**Issue by suketa** [suketa/ruby-duckdb#349]
fix append_blob test with duckdb 0.4.0

current test skipped because append_blob is failed.

```
$ TESTOPTS="--verbose" rake test
Run options: --verbose --seed 26009

... (snip)

  1) Skipped:
DuckDBTest::AppenderTest#test_append_blob [/home/suke/mywork/ruby-duckdb/test/duckdb_test/appender_test.rb:167]:
skip append_blob test with duckdb >= v0.4.0

  2) Skipped:
DuckDBTest::AppenderTest#test_append [/home/suke/mywork/ruby-duckdb/test/duckdb_test/appender_test.rb:401]:
skip append_blob test with duckdb >= v0.4.0

120 runs, 346 assertions, 0 failures, 0 errors, 2 skips
```

```
..................................................................................E..............E......................
Finished in 0.259127s, 463.0934 runs/s, 1335.2526 assertions/s.
  1) Error:
DuckDBTest::AppenderTest#test_append:
DuckDB::Error: failed to append
    /Users/runner/work/ruby-duckdb/ruby-duckdb/lib/duckdb/appender.rb:198:in `append_blob'
    /Users/runner/work/ruby-duckdb/ruby-duckdb/lib/duckdb/appender.rb:198:in `append'
    /Users/runner/work/ruby-duckdb/ruby-duckdb/test/duckdb_test/appender_test.rb:68:in `sub_test_append_column'
    /Users/runner/work/ruby-duckdb/ruby-duckdb/test/duckdb_test/appender_test.rb:391:in `test_append'
  2) Error:
DuckDBTest::AppenderTest#test_append_blob:
DuckDB::Error: failed to append
    /Users/runner/work/ruby-duckdb/ruby-duckdb/test/duckdb_test/appender_test.rb:72:in `append_blob'
    /Users/runner/work/ruby-duckdb/ruby-duckdb/test/duckdb_test/appender_test.rb:72:in `sub_test_append_column'
    /Users/runner/work/ruby-duckdb/ruby-duckdb/test/duckdb_test/appender_test.rb:162:in `test_append_blob'
120 runs, 346 assertions, 0 failures, 2 errors, 0 skips
```

**Comment by suketa** [comment]
failed of because of data includes 0x00.

**Comment by suketa** [comment]
This issue was fixed by https://github.com/duckdb/duckdb/pull/3961
