### ISSUE TITLE
Install failing on docker

### ISSUE THREAD

**Issue by suaron** [suketa/ruby-duckdb#720]
I want to install duckdb gem inside Docker

Bellow You can find useful information.

Partial content of Dockerfile
```Dockerfile
FROM ruby:3.2.2-bookworm

ARG DUCKDB_VERSION=1.0.0

.....

RUN wget https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/libduckdb-linux-amd64.zip
RUN unzip libduckdb-linux-amd64.zip -d libduckdb
RUN mv libduckdb/duckdb.* /usr/local/include
RUN mv libduckdb/libduckdb.so /usr/local/lib
RUN ldconfig --verbose /usr/local/lib

...
````

Install command
```sh
gem install duckdb -- --with-duckdb-include=/usr/local/include --with-duckdb-lib=/usr/local/lib
```

Errors
```log
Building native extensions with: '--with-duckdb-include=/usr/local/include --with-duckdb-lib=/usr/local/lib'
This could take a while...
ERROR:  Error installing duckdb:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/duckdb-1.0.0.2/ext/duckdb
/usr/local/bin/ruby extconf.rb --with-duckdb-include\=/usr/local/include --with-duckdb-lib\=/usr/local/lib
checking for duckdb.h in /opt/homebrew/include,/opt/homebrew/opt/duckdb/include,/opt/local/include... yes
checking for duckdb_bind_parameter_index() in -lduckdb... no
checking for duckdb_bind_parameter_index() in duckdb.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-duckdb-dir
        --without-duckdb-dir
        --with-duckdb-include=${duckdb-dir}/include
        --with-duckdb-lib=${duckdb-dir}/lib
        --with-duckdblib
        --without-duckdblib
extconf.rb:39:in `raise_not_found_library': libduckdb.so is not found. Install libduckdb.so of duckdb >= 0.9.0. (RuntimeError)
        from extconf.rb:32:in `check_duckdb_library'
        from extconf.rb:59:in `<main>'

********************************************************************************
libduckdb.so is not found. Install libduckdb.so of duckdb >= 0.9.0.
********************************************************************************


To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/aarch64-linux/3.2.0/duckdb-1.0.0.2/mkmf.log

extconf failed, exit code 1

```

Files
```
root@857682007b8f:/app# ls -la /usr/local/include | grep duck
-rw-r--r-- 1 root root  113598 May 30 08:51 duckdb.h
-rw-r--r-- 1 root root 1165439 May 30 09:07 duckdb.hpp


root@857682007b8f:/app# ls -la /usr/local/lib | grep duck
-rwxr-xr-x 1 root root 52829168 May 30 09:07 libduckdb.so
```

```sh
root@857682007b8f:/app# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```sh
root@857682007b8f:/app# uname -a
Linux 857682007b8f 6.6.26-linuxkit #1 SMP Sat Apr 27 04:13:19 UTC 2024 aarch64 GNU/Linux
```

**Comment by suaron** [comment]
Issue resolved. Invalid architecture  `libduckdb-linux-amd64.zip` should be `libduckdb-linux-aarch64.zip`.
